# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 21:01
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='课程标题')),
                ('course_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='课程介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='课程添加时间')),
                ('duration_time', models.FloatField(blank=True, null=True, verbose_name='课程时长')),
                ('class_num', models.IntegerField(blank=True, null=True, verbose_name='课时数')),
                ('play_num', models.IntegerField(blank=True, null=True, verbose_name='播放量')),
                ('up_num', models.IntegerField(blank=True, null=True, verbose_name='点赞量')),
                ('cost_money', models.FloatField(blank=True, null=True, verbose_name='课程费用')),
            ],
            options={
                'verbose_name': '课程基础信息',
                'verbose_name_plural': '课程基础信息',
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='课时标题')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='课时上架时间')),
                ('play_num', models.IntegerField(blank=True, null=True, verbose_name='播放量')),
                ('up_num', models.IntegerField(blank=True, null=True, verbose_name='点赞量')),
                ('cost_money', models.FloatField(blank=True, null=True, verbose_name='课程费用')),
            ],
            options={
                'verbose_name': '课程明细',
                'verbose_name_plural': '课程明细',
            },
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/banner', verbose_name='图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程图片',
                'verbose_name_plural': '课程图片',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='回复内容')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='讲师简介')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
            },
        ),
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField(verbose_name='是否赞')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDetail', verbose_name='点赞课程')),
            ],
        ),
    ]
