# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180414_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursebase',
            old_name='title',
            new_name='course_title',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='coursebase',
            name='course_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.TeacherProfile', verbose_name='课程医师'),
            preserve_default=False,
        ),
    ]
