# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180414_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='tag_index',
            field=models.IntegerField(default=0, unique=True, verbose_name='权重排序'),
        ),
    ]
